### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by larmort** [nilsnolde/ORStools#10]
I have used OSM tools for a few days, and I like it very much. But all of a sudden it stoped working. I have reinstalled both QGIS and OSM Tools several times, but the problems are still there. The problems are:

When I make a layer with Points and store it with CRS EPSG 4326 and run the accessibility analyse I get a message saying "TypeError: 'NoneType' object is not iterable".

When I starts the accessibility analyse and click "Map Now!" button and make a point on the map (regardless CRS, have tried several times with both EPSG 4326 and others) I allways get a message saying that the request is not valid because the coordinates can't be more than 1 km from a road. The point is placed in the senter of the roads. I have tried with both OSM and other map layers that have worked before.

**Comment by nilsnolde** [comment]
Yes, there seemed to be an issue yesterday with the API in general. I just tried re-downloaded the version from plugin repo and tried it out. It´s working fine on my side. 

I tried it a few times now and it really is a bit shaky.. The exact same operation sometimes works, sometimes doesn´t and reports the same error as you do here. It has to be a backend problem. I´ll save a few hours end of the week to go through this issue and all the others.

In the meantime, try it more than once with the exact same configuration and you might get lucky (as I did).  Also, I think you don´t have to dissolve anymore. More on that later. 

You did get your own API key, right? To eliminate that that´s not an issue.

Cheers
Nils

**Comment by larmort** [comment]
Thank you so much for your replay.

I have tried  the same operation several times as you recommended, but I haven't had any success yet. 

As for the question about the API key I automatically received a key when I installed the plugin. Before this problem appeared I once got a error saying that there was an issue with the key, but when i ran the same operation once more time it worked fine. I don't get any error messages saying anything about the key. I see there is a link to get a new key in the plugin, and in order to get a new key I need to register on the website. I have not done that. Is this necessary for me to do? Could reinstalling the plugin create a API key problem? I have reinstalled the plugin several times.

Once again thank you so much for your time and replay. I'm looking forward to this plugin working again, because it is a very good plugin.

**Comment by nilsnolde** [comment]
Hi again,

no worries, I´m fairly new to the whole plugin development myself, so I´m still pretty concerned with user experience;) Apparently that changes with time, but I´ll try to keep it up.

So, first things first:
You need to get your own API key. I provided one with the plugin. You didn´t receive an API key, it was just there, because I forgot to delete mine. But they disabled that one, since they want everyone who uses their service to subscribe. So, you need to use the ORS HP to apply for one. If it doesn´t arrive, you can contact the ORS guys on their google group. When you've done that and there´s still an issue, please revert. If it works, please close this issue.

And thanks for cheering btw:)

**Comment by riccardoklinger** [comment]
Have you obtained an own API key? Or do you use the prefilled one?

Von meinem iPhone gesendet

**Comment by larmort** [comment]
Once again: Thank you so mouch for your replay.

I have registered and requested my own API key yesterday, but I haven't received it yet. I will try to contact the ORS guys on this matter as advised.

**Comment by larmort** [comment]
Now I have received the API key and now the plugin works. I experience the "list index out of range" problem mentioned in case #8, even though my QGIS-installation only is a couple of days old. But even though I get the error message it seems to me that the isochrone gets right anyway. 

Thank you so much for your help.

**Comment by nilsnolde** [comment]
Hi Morten,

happy to hear that. To clarify: you see issue #8
<https://github.com/nilsnolde/ORStools/issues/8>, but the isochrones are
displayed correctly? I.e. you configure multiple isochrones and the
resulting shapefile actually has multiple features?

I´ll work now on removing the dissolve option, so that should be gone with
the next version.

Cheers
Nils
