### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by fgillen01** [nilsnolde/ORStools#19]
Plugin times out and nothing appears. Below is the error I get.

ConnectionError: HTTPSConnectionPool(host='api.openrouteservice.org', port=443): Max retries exceeded with url: /isochrones?api_key=58d904a497c67e00015b45fc6a689c6e3eb642b17542516ec88c1c4e&range_type=time&range=600.0&interval=300.0&profile=driving-car&location_type=start&locations=-6.22484,53.44515%7C-6.23635,53.28606 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000001FD59F98>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by nilsnolde** [comment]
Hi Finbar,

I can´t reproduce the issue. I used the exact [same setup](https://api.openrouteservice.org/isochrones?api_key=yourkey&range_type=time&range=3600.0&interval=900.0&profile=driving-car&location_type=start&locations=-6.22484,53.44515%7C-6.23635,53.28606) as you and it´s working:
![image](https://cloud.githubusercontent.com/assets/25637358/26643019/299ba608-4630-11e7-9402-8f767b81491c.png)

I can only guess that your internet connection is the culprit here.
